axess_client_portal/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('file-submission', views.file_submission, name='file-submission'),
    path('document-upload', views.document_upload, name='document-upload'),
    path('referral', views.referral, name='referral'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth')
]

axess_client_portal/axess_client_portal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    #path('login/', user_views.CustomLoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('login/', user_views.user_login, name='login'),
    path('password_change/', user_views.change_password, name='password_change'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # path('logout/', user_views.user_logout, name='logout'),
    path('', include(('client_portal.urls', 'client_portal'), namespace='client_portal')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api'))
]

axess_client_portal/client_portal/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions, name='transactions'),
    #path('transactions/<int:page_number>', views.transactions, name='transactions'),
    path('transactions/<str:transaction_id>', views.transaction_details, name='transaction-details'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<str:opportunity_id>', views.task_details, name='task-details'),
    path('send-email/', views.send_email, name='send-email'),
    path('send-message-to-clerk/', views.send_message_to_clerk, name='send-message-to-clerk'),
    path('profile/', views.profile, name='profile'),
    path('document-upload/', views.document_upload, name = 'document-upload'),
    path('modal-document-upload/', views.modal_document_upload, name = 'modal-document-upload'),
    path('file/', views.file, name = 'file'),
    path('sync/', views.sync, name = 'sync')
]
 

axess_client_portal/templates/includes/footer.html
{% load crispy_forms_tags %} 

<div class="modal fade" id="contact-us-popup" tabindex="-1" aria-labelledby="contact-us-popup"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>How can we help?</h4>
                <form class="mt-3 needs-validation" method="POST" action='{% url 'client_portal:send-email' %}'>
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="contact_id" value="{{ user.contact_id }}">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="email" value="{{ user.email }}">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="bdm_email" value="{{ bdm_email }}">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="3" name="comment" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary btn-md px-4 float-right">Submit</button>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="document-upload-popup" tabindex="-1" aria-labelledby="document-upload-popup" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Document Upload</h4>
                <form class="mt-3 needs-validation" enctype="multipart/form-data" method="POST" action='{% url 'client_portal:modal-document-upload' %}' id="document-upload-popup-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="transaction_id" id="document_upload_modal_transaction_id">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="task_api" id="document_upload_modal_task_api">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="task_value" id="document_upload_modal_task_value">
                    </div>
                    <div class="form-group">
                        <input type="file" class="form-control" name="file" multiple required id="document_upload_modal_file" accept=
                        "application/msword, application/vnd.ms-excel, application/vnd.ms-powerpoint,
                        text/plain, application/pdf, image/*">
                    </div>
                    <button type="submit" class="btn btn-primary btn-md px-4 float-right">Upload</button>
                </form>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="task-detail-modal" tabindex="-1" aria-labelledby="task-detail-modal"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Task Details</h4>
                
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="message-clerk-modal" tabindex="-1" aria-labelledby="message-clerk-modal"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header d-flex align-items-center">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Your Message To <span id="send_email_to_clerk_clerk_name"></span></h4>
                <form class="mt-3 needs-validation" method="POST" action='{% url 'client_portal:send-message-to-clerk' %}'>
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="contact_id" value="{{ user.contact_id }}">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="email" value="{{ user.email }}">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="transaction_id" id="send_email_to_clerk_transaction_id">
                    </div>
                    <div class="form-group">
                        <input type="hidden" class="form-control hidden" name="clerk_email" id="send_email_to_clerk_clerk_email">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="3" name="comment" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary btn-md px-4 float-right">Send</button>
                </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    {% now "Y" %}© Axess Law Professional Corporation. <br>All Rights Reserved.
</footer>

axess_client_portal/templates/includes/footer_scripts.html
{% load static %}

<script src='{% static 'assets/libs/jquery/dist/jquery.min.js' %}'></script>
<!-- Bootstrap tether Core JavaScript -->
<script src='{% static 'assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}'></script>
<!-- apps -->
<script src='{% static 'js/app.min.js' %}'></script>
<script src='{% static 'js/app.init.js' %}'></script>
<script src='{% static 'js/app-style-switcher.js' %}'></script>
<!-- slimscrollbar scrollbar JavaScript -->
<script src='{% static 'assets/libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js' %}'></script>
<script src='{% static 'assets/extra-libs/sparkline/sparkline.js' %}'></script>
<!--Wave Effects -->
<script src='{% static 'js/waves.js' %}'></script>
<!--Menu sidebar -->
<script src='{% static 'js/sidebarmenu.js' %}'></script>
<!--Custom JavaScript -->
<script src='{% static 'js/feather.min.js' %}'></script>
<script src='{% static 'js/custom.min.js' %}'></script>
<!--This page JavaScript -->
<script src='{% static 'assets/libs/apexcharts/dist/apexcharts.min.js' %}'></script>
<!-- Chart JS -->
<script src='{% static 'js/pages/dashboards/dashboard1.js' %}'></script>

<script src="https://cdn.jsdelivr.net/npm/vue"></script>

<script type="text/javascript">
    $('.open_message_clerk_modal').on('click', function (event) {
        var clerk_email = $(this).data('clerk-email'); // Extract info from data-* attributes
        var clerk_name = $(this).data('clerk-name');  
        var transaction_id = $(this).data('transaction-id');
        $('#send_email_to_clerk_clerk_email').val(clerk_email);
        $('#send_email_to_clerk_transaction_id').val(transaction_id);
        $('#send_email_to_clerk_clerk_name').text(clerk_name);
    })

    $('.open_document_upload_modal').on('click', function (event) {
        var transaction_id = $(this).data('transaction-id');
        var task_api = $(this).data('task-api');
        var task_value = $(this).data('task-value');
        $('#document_upload_modal_transaction_id').val(transaction_id);
        $('#document_upload_modal_task_api').val(task_api);
        $('#document_upload_modal_task_value').val(task_value);
        console.log('open_document_upload_modal clicked');
    })

    $('#document-upload-popup-form').submit(function(e){
        
        var upload_field_id = "document_upload_modal_file";
        var max_size_in_bytes = 37748736;
        var fld = document.getElementById(upload_field_id);
        e.preventDefault();
        var is_ok = true;
        for (var i = 0, file; file = fld.files[i]; i++ ) {
            console.log(file.size);
            console.log(file.type);
            
            if(file.size > max_size_in_bytes)
            { 
                alert("The file size must be no more than " + parseInt(max_size_in_bytes/1024/1024) + "MB");
                is_ok = false;
                break;                
            } 

            if(file.type == 'application/json' || file.type == 'text/html') {
                alert("JSON and HTML files are not allowed");
                is_ok = false;
                break;
            } 
        }

        console.log(is_ok);
        
        if(is_ok) {
            $('#document-upload-popup-form')[0].submit();
        }
        
    });

    $('#apply_transactions_filter').on('click', function (event) {
        var broker = $("#broker_name_filter").val(); 
        var status = $("#status_filter").val(); 
        var type = $("#transaction_type_filter").val(); 
        console.log(broker);
        console.log(status);
        console.log(type);
        let queries = ''
        if(broker || status || type) queries += '?';
        if(broker) queries += 'broker=' + broker;
        if(status) {
            queries += broker ? '&status=' + status : 'status=' + status;
        }
        if(type) {
            queries += status || broker ? '&type=' + type : 'type=' + type;
        }
        let url = window.location.pathname + queries;
        console.log(url);
        window.location.href = url;
    })

</script>

axess_client_portal/templates/includes/sidebar.html
{% load static %}
{% load filters %}

<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">
                    <i class="nav-small-line"></i>
                    <span class="hide-menu">QUICK ACCESS</span>
                </li>
              <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href='{% url 'client_portal:dashboard' %}' aria-expanded="false">
                        <i data-feather="grid"></i><span class="hide-menu">Dashboard</span><i class="hide-menu ri-arrow-right-s-fill"></i>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href='{% url 'client_portal:transactions' %}' aria-expanded="false">
                        <i data-feather="home"></i><span class="hide-menu">Transactions</span><i class="hide-menu ri-arrow-right-s-fill"></i>
                    </a>
                </li>
                <li class="sidebar-item"> 
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href='{% url 'client_portal:tasks' %}' aria-expanded="false">
                        <i data-feather="trello"></i><span class="hide-menu">My Tasks</span><i class="hide-menu ri-arrow-right-s-fill"></i>
                    </a>
                </li>
                <!-- <li class="sidebar-item"> 
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href='{% url 'client_portal:document-upload' %}' aria-expanded="false">
                        <i data-feather="check-square"></i><span class="hide-menu">Document Upload</span>
                    </a>
                </li> -->
                <li class="sidebar-item" style="display: none;"> 
                    <a class="sidebar-link waves-effect waves-dark sidebar-link" href="#" aria-expanded="false">
                        <i data-feather="help-circle"></i><span class="hide-menu">To Come</span>
                    </a>
                </li>

                {% comment %} <li class="sidebar-item"><br></li> {% endcomment %}
              
                {% comment %} <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                    href='{% url 'client_portal:sync' %}' aria-expanded="false"><i
                        class="fas fa-sync"></i><span class="hide-menu">ShiftPlanning Sync</span></a>
                </li> {% endcomment %}
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                    href='{% url 'password_change' %}' aria-expanded="false"><i
                        class="ri-lock-password-line"></i><span class="hide-menu">Change Password</span><i class="hide-menu ri-arrow-right-s-fill d-none"></i></a>
                </li>
                <li class="sidebar-item"> <a class="sidebar-link waves-effect waves-dark sidebar-link"
                    href='{% url 'logout' %}' aria-expanded="false"><i
                        data-feather="log-out"></i><span class="hide-menu">Log Out</span><i class="hide-menu ri-arrow-right-s-fill d-none"></i></a>
                </li>
                
                <!-- Display only if user logged in is Admin-->
                {% if user.is_superuser %}
                    <li class="nav-small-cap"><i class="nav-small-line"></i>
                        <span class="hide-menu">Admin</span>
                    </li>
                    <li class="sidebar-item"> 
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="#" aria-expanded="false">
                            <i data-feather="settings"></i><span class="hide-menu">Admin Tools</span>
                        </a>
                    </li>
                    <li class="sidebar-item"> 
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="#" aria-expanded="false">
                            <i data-feather="git-pull-request"></i><span class="hide-menu">Changelog</span>
                        </a>
                    </li>
                    <li class="sidebar-item"> 
                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="https://github.com/axesslaw/axess-client-portal" target="_blank" aria-expanded="false">
                            <i data-feather="github"></i><span class="hide-menu">GitHub</span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    <!-- Bottom points-->
    {% if user.is_client and bdm_email %}
        <div class="sidebar-footer px-3 py-4">
            <div class="bg-light-info buynow-card mb-0 mt-3 w-100"> 
                {% if bdm_email %}
                    {% with '/static/assets/images/users/'|add:bdm_email|add:'.png' as file_path %}
                        {% if file_path|file_exists %}
                            <img src='{% static 'assets/images/users/'|add:bdm_email|add:'.png' %}' class="mt-n5 buynow-img">
                        {% else %}
                            <img src='{% static 'assets/images/background/sidebar-buynow.png' %}' class="mt-n5 buynow-img">
                        {% endif %}
                    {% endwith %}
                {% else %}
                    <img src='{% static 'assets/images/background/sidebar-buynow.png' %}' class="mt-n5 buynow-img">
                {% endif %}
                <!-- <img src='{% static 'assets/images/background/sidebar-buynow.png' %}' class="mt-n5 buynow-img"> -->
                <div class="sidebar-footer-text">
                    <h4 class="fw-bold">Have a</h5>
                    <h4 class="fw-bold">Question?</h5>
                    <button type="button" class="btn btn-primary mt-2 px-4 fs-4" data-bs-toggle="modal" data-bs-target="#contact-us-popup">
                        Contact Your BDM
                    </button>
                </div>                    
            </div>
        </div>
    {% endif %}
    <!-- End Bottom points-->
</aside>