axess_client_portal/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('file-submission', views.file_submission, name='file-submission'),
    path('document-upload', views.document_upload, name='document-upload'),
    path('referral', views.referral, name='referral'),
    path('api-token-auth/', obtain_auth_token, name='api-token-auth')
]

axess_client_portal/axess_client_portal/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    #path('login/', user_views.CustomLoginView.as_view(template_name='users/login.html', redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('login/', user_views.user_login, name='login'),
    path('password_change/', user_views.change_password, name='password_change'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='reset_password'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    # path('logout/', user_views.user_logout, name='logout'),
    path('', include(('client_portal.urls', 'client_portal'), namespace='client_portal')),
    path('api/v1/', include(('api.urls', 'api'), namespace='api'))
]

axess_client_portal/client_portal/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('transactions/', views.transactions, name='transactions'),
    #path('transactions/<int:page_number>', views.transactions, name='transactions'),
    path('transactions/<str:transaction_id>', views.transaction_details, name='transaction-details'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/<str:opportunity_id>', views.task_details, name='task-details'),
    path('send-email/', views.send_email, name='send-email'),
    path('send-message-to-clerk/', views.send_message_to_clerk, name='send-message-to-clerk'),
    path('profile/', views.profile, name='profile'),
    path('document-upload/', views.document_upload, name = 'document-upload'),
    path('modal-document-upload/', views.modal_document_upload, name = 'modal-document-upload'),
    path('file/', views.file, name = 'file'),
    path('sync/', views.sync, name = 'sync')
]
 

axess_client_portal/client_portal/models.py
from django.db import models

# Create your models here.

axess_client_portal/client_portal/forms.py
from crispy_forms.layout import Submit
from django import forms
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.utils.translation import ugettext_lazy as _
from crispy_forms.helper import FormHelper
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = UsernameField(
        label='Email Address',
        widget=forms.TextInput(attrs={'autofocus': True})
    )

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_errors = False

        self.helper.add_input(Submit('submit', 'Login', css_class='btn btn-primary btn-lg px-4 mt-3'))



class UserRegisterForm(UserCreationForm):
    username = forms.EmailField(required=True, label='Email Address', max_length=100, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.')


    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
    
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        #self.fields['username'].help_text = 'Required. 150 characters or fewer.'

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data.get('username')
        if commit:
            print('saved!')
            user.save()
        else:
            print('not saved!')
        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'username': 'Username',
            'email': 'Email Address',
            'first_name': 'First Name',
            'last_name': 'Last Name'
        }


class UploadFileForm(forms.Form):
    file = forms.FileField()

axess_client_portal/client_portal/views.py
import requests, logging
from requests.api import get
from simple_salesforce.api import Salesforce
from users.decorators import admin_required
from django.shortcuts import render, redirect
from django.core.mail import send_mail, EmailMultiAlternatives
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.views import View
from django.contrib import messages, auth 
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.loader import render_to_string
from django_filters import FilterSet
from simple_salesforce import Salesforce, format_soql
from modules import salesforce
from users.models import User
from dotenv import load_dotenv
from os import getenv
from .forms import UploadFileForm

load_dotenv()

logger = logging.getLogger('watchtower')



# Create your views here.

@login_required(redirect_field_name=None)
def dashboard(request):
    recent_transactions = salesforce.get_recent_transactions(request, 1)
    if(recent_transactions['has_result']):
        most_recent_transaction_details = salesforce.get_transaction_details(request, recent_transactions['transactions'][0]['Opportunity']['Id'])
        if(most_recent_transaction_details['has_result']):
            transaction_info = salesforce.get_transaction_data(most_recent_transaction_details['transaction']['Opportunity']['RecordTypeId'])
            total_transactions = salesforce.get_all_transactions(request)
            transactions = recent_transactions['transactions']
            for transaction in transactions:
                tdata = salesforce.get_transaction_data(transaction['Opportunity']['RecordTypeId'])
                transaction['portal_transaction_type'] = tdata['label']
        
            context = {
                'transactions': transactions,
                'total_transactions': total_transactions['total'],
                'total_open_transactions': total_transactions['total_open'],
                'total_completed_transactions': total_transactions['total_completed'],
                'transactions_with_tasks_outstanding': recent_transactions['transactions_with_tasks_outstanding'],
                'most_recent_transaction': most_recent_transaction_details['transaction'],
                'most_recent_transaction_portal_type': most_recent_transaction_details['portal_transaction_type'],
                'number_of_completed_tasks': most_recent_transaction_details['number_of_completed_tasks'],
                'number_of_open_tasks': most_recent_transaction_details['number_of_open_tasks'],
                'completed_tasks': most_recent_transaction_details['completed_tasks'],
                'open_tasks': most_recent_transaction_details['open_tasks'],
                'milestones': transaction_info['milestones'] if transaction_info else [],
                'current_milestone_index': (transaction_info['milestones'].index(most_recent_transaction_details['transaction']['Opportunity']['Milestone__c'])) + 1 if transaction_info and most_recent_transaction_details['transaction']['Opportunity']['Milestone__c'] else 1
            }

        else:
            context = {
                'no_recent_transactions': True,
                'error': "You don't have any recent transactions to view.",
                'transactions_with_tasks_outstanding': 0
            }
    else:
        print('No result found')
        context = {
            'no_recent_transactions': True,
            'error': "You don't have any recent transactions to view.",
            'transactions_with_tasks_outstanding': 0
        }

    return render(request, 'client_portal/index.html', context)


@login_required(redirect_field_name=None)
def transactions(request, page_number=1):
    page_size = 5
    
    all_transactions = salesforce.get_all_transactions(request)

    current_page = request.GET.get('page')
    if(current_page):
        page_number = current_page
    
    if(all_transactions['has_result']):
        total_transactions = all_transactions['total']
        total_open_transactions = all_transactions['total_open']
        total_completed_transactions = all_transactions['total_completed']
        transactions = all_transactions['transactions']
        brokers = all_transactions['brokers']
        for transaction in transactions:
            tdata = salesforce.get_transaction_data(transaction['Opportunity']['RecordTypeId'])
            transaction['portal_transaction_type'] = tdata.get('label')
            
        all_transactions = tuple(transactions)

        paginator = Paginator(all_transactions, page_size)
        
        try: 
            transactions = paginator.page(page_number)
        except PageNotAnInteger:
            transactions = paginator.page(1)
        except EmptyPage:
            transactions = paginator.page(paginator.num_pages)    

        context = {
            'transactions': transactions,
            'total_transactions': total_transactions,
            'total_open_transactions': total_open_transactions,
            'total_completed_transactions': total_completed_transactions,
            'brokers': brokers
        }
    else:
        print('No transactions at all')
        context = {
            'error': "You don't have any transactions to view."
        }

    return render(request, 'client_portal/transactions.html', context)
    

@login_required(redirect_field_name=None)
def tasks(request, page_number=1):
    page_size = 5
    all_transactions = salesforce.get_all_transactions_with_tasks_outstanding(request)
    if(all_transactions['has_result']):
        transactions = all_transactions['transactions']
        for transaction in transactions:
            tdata = salesforce.get_transaction_data(transaction['Opportunity']['RecordTypeId'])
            transaction['portal_transaction_type'] = tdata['label']
            
        all_transactions = tuple(transactions)
        paginator = Paginator(all_transactions, page_size)
        
        try: 
            transactions = paginator.page(page_number)
        except PageNotAnInteger:
            transactions = paginator.page(1)
        except EmptyPage:
            transactions = paginator.page(paginator.num_pages)    

        context = {
            'transactions': transactions
        }
    else:
        print('No Transactions with Tasks Outstanding')
        context = {
            'error': "You don't have any Transactions with Tasks Outstanding."
        }

    return render(request, 'client_portal/tasks.html', context)


@login_required(redirect_field_name=None)
def transaction_details(request, transaction_id):
    if(transaction_id.startswith('006') and len(transaction_id) == 18):
        get_transaction_details = salesforce.get_transaction_details(request, transaction_id)
        form = UploadFileForm()
        if(get_transaction_details['has_result']):
            sf_transaction_type = get_transaction_details['transaction']['Opportunity']['Lead_Transaction_Type__c']
            transaction_info = salesforce.get_transaction_data(get_transaction_details['transaction']['Opportunity']['RecordTypeId'])
            clerk_info = salesforce.get_clerk_data(get_transaction_details['transaction']['Opportunity']['Clerk_Assigned_Email_Address__c'])
            bdm_info = salesforce.get_bdm_data(get_transaction_details['transaction']['Opportunity']['BDM__c'])
            context = {
                'transaction_id': transaction_id,
                'transaction': get_transaction_details['transaction'],
                'tasks': get_transaction_details['tasks'],
                'number_of_completed_tasks': get_transaction_details['number_of_completed_tasks'],
                'number_of_open_tasks': get_transaction_details['number_of_open_tasks'],
                'completed_tasks': get_transaction_details['completed_tasks'],
                'open_tasks': get_transaction_details['open_tasks'],
                'form': form,
                'portal_transaction_type': get_transaction_details['portal_transaction_type'],
                'clerk_phone_number': clerk_info['phone'] if clerk_info else '',
                'bdm_email': bdm_info['email'] if bdm_info else '',
                'milestones': transaction_info['milestones'] if transaction_info else [],
                'current_milestone_index': (transaction_info['milestones'].index(get_transaction_details['transaction']['Opportunity']['Milestone__c'])) + 1 if transaction_info and get_transaction_details['transaction']['Opportunity']['Milestone__c'] else 1,
                'primary_contact': get_transaction_details['primary_contact']
            }
        else:
            print('No result found')
            context = {
                'transaction_id': transaction_id,
                'error': "You don't have permissions to view this record or the record does not exist."
            }
    else:
        context = {
            'transaction_id': transaction_id,
            'error': 'Transaction Id is not correct.'
        }
    
    return render(request, 'client_portal/transaction_details.html', context)


@login_required(redirect_field_name=None)
def task_details(request, opportunity_id):
    if(opportunity_id.startswith('006') and len(opportunity_id) == 18):
        get_task_details = salesforce.get_task_details(request, opportunity_id)
        if(get_task_details['has_result']):
            context = {
                'opportunity_id': opportunity_id,
                'tasks': get_task_details['tasks'],
                'transaction': get_task_details['transaction'],
            }
        else:
            print('No result found')
            context = {
                'opportunity_id': opportunity_id,
                'error': "You don't have permissions to view this record or the record does not exist."
            }
    else:
        context = {
            'opportunity_id': opportunity_id,
            'error': 'Opportunity Id is not correct.'

axess_client_portal/client_portal/templates/client_portal/partials/admin_dashboard.html
{% load static %}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-titles">
        <div class="row">
            <div class="col-lg-8 col-md-6 col-12 align-self-center">
                <div><span class="welcome">Welcome</span> <span class="welcome-name">{{ user.first_name }}</span></div>
                {% comment %} <h1 class="mb-0 fw-bold">
                    Admin Dashboard
                </h1> {% endcomment %}
                <span class="account-summary">
                    Your account summary as on {% now "D, jS F Y" %}
                </span>
            </div>

            <div class="col-lg-4 col-md-6 d-none d-md-flex align-items-center justify-content-end">
                {% comment %} {% now "F d, Y" %} {% endcomment %}
                {% comment %} <a href='{% url 'client_portal:file' %}' class="btn btn-info d-flex align-items-center ms-2">
                    <i class="ri-add-line me-1"></i>
                    Start a File
                </a> {% endcomment %}
            </div>
        </div>
    </div>

    {% include 'client_portal/partials/messages.html' %}

    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-3">
                <div class="d-flex align-items-stretch">
                    <!-- earnings card -->
                    <div class="card bg-primary w-100" id="blue-box-outstanding-tasks">
                        <div class="card-body card-hover">
                            <a href='{% url 'client_portal:tasks' %}'>
                                <div class="d-flex align-items-center">
                                    <h4 class="card-title text-white">Tasks</h4>
                                    <div class="ms-auto">
                                        <span class="btn btn-lg btn-info btn-circle d-flex align-items-center justify-content-center">
                                            <i data-feather="check-circle"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <h2 class="fs-8 text-white mb-0">{{ transactions_with_tasks_outstanding }}</h2>
                                    <span class="text-white op-5">Transactions with Tasks outstanding</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-stretch" style="display:none!important;">
                    <!-- monthly sales card -->
                    <div class="card w-100 overflow-hidden">
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                <div>
                                    <h5 class="fw-normal mb-0 text-muted">Monthly Sales</h5>
                                    <h2 class="mb-0">3246</h2>
                                </div>
                                <div class="ms-auto">
                                    <span class="btn btn-lg btn-warning btn-circle d-flex align-items-center justify-content-center">
                                        <i data-feather="shopping-bag"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- chart -->
                        <div id="monthly-sales"></div>
                    </div>
                </div>
            </div>

            <!-- TABLE RIGHT -->
            
            {% include 'client_portal/partials/recent_transactions_table.html' %}

        </div>
        <!-- Row -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->

    {% include 'includes/footer.html' %}
</div>

axess_client_portal/client_portal/templates/client_portal/partials/client_dashboard.html
{% load static %}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-titles">
        <div class="row">
            <div class="col-lg-8 col-md-6 col-12 align-self-center">
                <div><span class="welcome">Welcome</span> <span class="welcome-name">{{ user.first_name }}</span></div>
                {% comment %} <h1 class="mb-0 fw-bold">
                    Client Dashboard
                </h1> {% endcomment %}
                <span class="account-summary">
                    Your account summary as on {% now "D, jS F Y" %}
                </span>
            </div>

            <div class="col-lg-4 col-md-6 d-none d-md-flex align-items-center justify-content-end">
                {% comment %} {% now "F d, Y" %} {% endcomment %}
                {% comment %} <a href='{% url 'client_portal:file' %}' class="btn btn-info d-flex align-items-center ms-2" style="display: none!important;">
                    <i class="ri-add-line me-1"></i>
                    Start a File
                </a> {% endcomment %}
            </div>
        </div>
    </div>

    {% include 'client_portal/partials/messages.html' %}

    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-3">
                <div class="d-flex align-items-stretch">
                    <!-- earnings card -->
                    <div class="card bg-primary w-100" id="blue-box-outstanding-tasks">
                        <div class="card-body card-hover">
                            <a href='{% url 'client_portal:tasks' %}'>
                                <div class="d-flex align-items-center">
                                    <h4 class="card-title text-white">Tasks</h4>
                                    <div class="ms-auto">
                                        <span class="btn btn-lg btn-info btn-circle d-flex align-items-center justify-content-center">
                                            <i data-feather="check-circle"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <h2 class="fs-8 text-white mb-0">{{ transactions_with_tasks_outstanding }}</h2>
                                    <span class="text-white op-5">Transactions with Tasks outstanding</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-stretch" style="display:none!important;">
                    <!-- monthly sales card -->
                    <div class="card w-100 overflow-hidden">
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                <div>
                                    <h5 class="fw-normal mb-0 text-muted">Monthly Sales</h5>
                                    <h2 class="mb-0">3246</h2>
                                </div>
                                <div class="ms-auto">
                                    <span class="btn btn-lg btn-warning btn-circle d-flex align-items-center justify-content-center">
                                        <i data-feather="shopping-bag"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- chart -->
                        <div id="monthly-sales"></div>
                    </div>
                </div>
            </div>

            <!-- TABLE RIGHT -->
            
            {% include 'client_portal/partials/recent_transactions_table.html' %}

        </div>
        <!-- Row -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->

    {% include 'includes/footer.html' %}
</div>

axess_client_portal/client_portal/templates/client_portal/partials/employee_dashboard.html
{% load static %}

<div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <div class="page-titles">
        <div class="row">
            <div class="col-lg-8 col-md-6 col-12 align-self-center">
                <div><span class="welcome">Welcome</span> <span class="welcome-name">{{ user.first_name }}</span></div>
                {% comment %} <h1 class="mb-0 fw-bold">
                    Employee Dashboard
                </h1> {% endcomment %}
                <span class="account-summary">
                    Your account summary as on {% now "D, jS F Y" %}
                </span>
            </div>

            <div class="col-lg-4 col-md-6 d-none d-md-flex align-items-center justify-content-end">
                {% comment %} {% now "F d, Y" %} {% endcomment %}
                {% comment %} <a href='{% url 'client_portal:file' %}' class="btn btn-info d-flex align-items-center ms-2">
                    <i class="ri-add-line me-1"></i>
                    Start a File
                </a> {% endcomment %}
            </div>
        </div>
    </div>

    {% include 'client_portal/partials/messages.html' %}
    
    <!-- ============================================================== -->
    <!-- End Bread crumb and right sidebar toggle -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- Row -->
        <div class="row">
            <!-- Column -->
            <div class="col-lg-3">
                <div class="d-flex align-items-stretch">
                    <!-- earnings card -->
                    <div class="card bg-primary w-100" id="blue-box-outstanding-tasks">
                        <div class="card-body card-hover">
                            <a href='{% url 'client_portal:tasks' %}'>
                                <div class="d-flex align-items-center">
                                    <h4 class="card-title text-white">Tasks</h4>
                                    <div class="ms-auto">
                                        <span class="btn btn-lg btn-info btn-circle d-flex align-items-center justify-content-center">
                                            <i data-feather="check-circle"></i>
                                        </span>
                                    </div>
                                </div>
                                <div class="mt-3">
                                    <h2 class="fs-8 text-white mb-0">{{ transactions_with_tasks_outstanding }}</h2>
                                    <span class="text-white op-5">Transactions with Tasks outstanding</span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-stretch" style="display:none!important;">
                    <!-- monthly sales card -->
                    <div class="card w-100 overflow-hidden">
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                <div>
                                    <h5 class="fw-normal mb-0 text-muted">Monthly Sales</h5>
                                    <h2 class="mb-0">3246</h2>
                                </div>
                                <div class="ms-auto">
                                    <span class="btn btn-lg btn-warning btn-circle d-flex align-items-center justify-content-center">
                                        <i data-feather="shopping-bag"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <!-- chart -->
                        <div id="monthly-sales"></div>
                    </div>
                </div>
            </div>

            <!-- TABLE RIGHT -->
            
            {% include 'client_portal/partials/recent_transactions_table.html' %}

        </div>
        <!-- Row -->
    </div>
    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->

    {% include 'includes/footer.html' %}
</div>

axess_client_portal/client_portal/templates/client_portal/partials/messages.html
{% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-bs-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}